track_it_all/bugs/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField, SelectField
from wtforms.validators import DataRequired

from track_it_all.bugs.utils import Bug_Status, Bug_Priority
from track_it_all.models import Bug, Project

class BugForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    about = TextAreaField('Description', validators=[DataRequired()])
    bug_status = SelectField(
        'Status',
        choices=[],
        validators=[DataRequired(message="Please select a status.")]
    )
    priority = SelectField(
        'Priority',
        choices=[(priority.value, priority.value) for priority in Bug_Priority],
        validators=[DataRequired(message="Please select a priority.")]
    )
    user_assigned = SelectField(
        'Assigned User',
        choices=[],
        validators=[DataRequired(message="Please select a user.")]
    )

    submit = SubmitField('Submit')

    def __init__(self, project_id, creator_user, request_method='POST', *args, **kwargs):
        super(BugForm, self).__init__(*args, **kwargs)
        self.project_id = project_id
        self.request_method = request_method
        self.user_assigned.choices = [
            (user.id, user.first_name) \
                for user in Project.query.get(project_id).get_all_users() \
                    if user.id != Project.query.get(project_id).manager().id
                    ]
        if creator_user.get_role(project_id) == 'Developer':
            self.bug_status.choices = [
                (status.value, status.value) for status in Bug_Status if status not in [Bug_Status.VERIFIED, Bug_Status.CLOSED]
            ]
        elif creator_user.get_role(project_id) == 'Tester' or creator_user.get_role(project_id) == 'Designer':
            self.bug_status.choices = [
                (status.value, status.value) for status in Bug_Status if status not in [Bug_Status.CLOSED]
            ]
        else:
            self.bug_status.choices = [
                (status.value, status.value) for status in Bug_Status
            ] 

    def validate(self, extra_validators=None):
        initial_validation = super(BugForm, self).validate(extra_validators)
        if not FlaskForm.validate(self):
            return False
        if self.request_method == 'POST':
            bugs = Bug.query.filter_by(project=self.project_id).all()
            for bug in bugs:
                if bug.title == self.title.data and self.about.data == bug.about:
                    self.title.errors.append('Bug already exists with that title and description.')
                    self.about.errors.append('Bug already exists with that title and description.')
                    return False
        return True

track_it_all/bugs/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort
from flask_login import login_required, current_user

from track_it_all.models import Bug, User, Project
from track_it_all import db
from track_it_all.bugs.forms import BugForm

bugs = Blueprint('bugs', __name__)

@bugs.route('/add-bug/<string:project_id>', methods=['GET', 'POST'])
@login_required
def add_bug(project_id):
    project = Project.query.get_or_404(project_id)
    if current_user not in project.get_all_users():
        abort(403)
    form = BugForm(project_id=project_id, creator_user=current_user)
    if form.validate_on_submit():
        bug = Bug(
            title=form.title.data, 
            about=form.about.data,
            bug_status=form.bug_status.data,
            priority=form.priority.data,
            user_assigned=form.user_assigned.data,
            project=project.id,
            created_by=str(current_user.id),
            updated_by=str(current_user.id)
            )
        db.session.add(bug)
        db.session.commit()
        flash('Bug added to project!', category='success')
        return redirect(url_for('projects.get_project', project_id=project.id))
    return render_template('add_bug.html', user=current_user, form=form, legend='Add Bug')

@bugs.route('bug/get/<string:bug_id>')
@login_required
def get_bug(bug_id):
    bug = Bug.query.get_or_404(bug_id)
    user_assigned = User.query.get(bug.user_assigned) if bug.user_assigned else None
    return render_template('bug.html', user=current_user, bug=bug, user_assigned=user_assigned)

@bugs.route('bug/update/<string:bug_id>', methods=['GET', 'POST'])
@login_required
def update_bug(bug_id):
    bug = Bug.query.get_or_404(bug_id)
    if current_user not in Project.query.get(bug.project).get_all_users():
        abort(403)
    method = request.form.get('_method')
    form = BugForm(project_id=bug.project, request_method=method, creator_user=current_user)
    if form.validate_on_submit():
        bug.title = form.title.data
        bug.about = form.about.data
        bug.bug_status = form.bug_status.data
        bug.priority = form.priority.data
        bug.user_assigned = form.user_assigned.data
        bug.updated_by = str(current_user.id)
        db.session.commit()
        flash('Bug updated!', category='success')
        return redirect(url_for('bugs.get_bug', bug_id=bug.id))
    elif request.method == 'GET':
        form.title.data = bug.title
        form.about.data = bug.about
        form.bug_status.data = bug.bug_status
        form.priority.data = bug.priority
        form.user_assigned.data = bug.user_assigned
        form.submit.label.text = 'Update'
    return render_template('add_bug.html', user=current_user, form=form, legend='Update Bug')

@bugs.route('bug/delete/<string:bug_id>', methods=['GET','POST'])
@login_required
def delete_bug(bug_id):
    bug = Bug.query.get_or_404(bug_id)
    if current_user not in Project.query.get(bug.project).get_all_users():
        abort(403)
    db.session.delete(bug)
    db.session.commit()
    flash('Bug deleted!', category='success')
    return redirect(url_for('projects.get_project', project_id=bug.project))

@bugs.route('/user/<string:user_id>')
@login_required
def user_bugs(user_id):
    page = request.args.get('page', 1, type=int)
    user = User.query.get_or_404(user_id)
    bugs = user.bugs.order_by(Bug.created_at.desc()).paginate(page=page, per_page=5)
    return render_template('user_bugs.html', user=user, bugs=bugs)

track_it_all/projects/routes.py
import uuid
from flask import Blueprint, render_template, request, redirect, url_for, flash, abort
from flask_login import login_required, current_user

from track_it_all.models import Project, Bug, User, project_user
from track_it_all import db
from track_it_all.projects.forms import ProjectForm, ProjectUserForm
from track_it_all.projects.utils import Project_Roles

projects = Blueprint('projects', __name__)

@projects.route('/add-project', methods=['GET', 'POST'])
@login_required
def add_project():
    form = ProjectForm()
    if form.validate_on_submit():
        project = Project(
            name=form.name.data, 
            about=form.about.data, 
            personal=form.personal.data,
            group_project=form.group_project.data,
            created_by=str(current_user.id), 
            updated_by=str(current_user.id)
            )
        db.session.add(project)
        db.session.commit()

        project_user_row = project_user.insert().values(
            project_id=project.id, 
            user_id=current_user.id, 
            user_role=Project_Roles.MANAGER.value,
            created_by=current_user.id,
            updated_by=current_user.id
            )
        db.session.execute(project_user_row)
        db.session.commit()

        flash('Project added!', category='success')
        return redirect(url_for('main.home'))
    return render_template('add_project.html', user=current_user, form=form, legend='Add Project')

@projects.route('/get-project/<string:project_id>', methods=['GET', 'POST'])
@login_required
def get_project(project_id):
    project = Project.query.get_or_404(project_id)
    return render_template('project.html', user=current_user, project=project)

@projects.route('/update-project/<string:project_id>', methods=['GET', 'POST'])
@login_required
def update_project(project_id):
    project = Project.query.get_or_404(project_id)
    if project.manager().id != current_user.id:
        abort(403)
    form = ProjectForm()
    if form.validate_on_submit():
        project.name = form.name.data
        project.about = form.about.data
        project.personal = form.personal.data
        project.group_project = form.group_project.data
        project.updated_by = str(current_user.id)
        db.session.commit()
        flash('Project updated!', category='success')
        return redirect(url_for('projects.get_project', project_id=project.id))
    elif request.method == 'GET':
        form.name.data = project.name
        form.about.data = project.about
        form.personal.data = project.personal
        form.group_project.data = project.group_project
    return render_template('add_project.html', user=current_user, form=form, legend='Update Project')

@projects.route('/delete-project/<string:project_id>', methods=['GET', 'POST'])
@login_required
def delete_project(project_id):
    project = Project.query.get_or_404(project_id)
    if project.manager().id != current_user.id:
        abort(403)
    db.session.delete(project)
    db.session.commit()
    flash('Project deleted!', category='success')
    return redirect(url_for('main.home'))

@projects.route('/user-projects/<string:user_id>')
@login_required
def user_projects(user_id):
    page = request.args.get('page', 1, type=int)
    user = User.query.get_or_404(user_id)
    projects = user.get_all_projects().paginate(page=page, per_page=5)
    return render_template('user_projects.html', user=current_user, projects=projects)

@projects.route('/add-user-to-project/<string:project_id>', methods=['GET', 'POST'])
@login_required
def add_user_to_project(project_id):
    project = Project.query.get_or_404(project_id)
    if project.manager().id != current_user.id:
        abort(403)
    form = ProjectUserForm(project_id)
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        project_user_row = project_user.insert().values(
            project_id=project.id, 
            user_id=user.id, 
            user_role=form.role.data,
            created_by=current_user,
            updated_by=current_user
            )
        db.session.execute(project_user_row)
        db.session.commit()
        flash('User added to project!', category='success')
        return redirect(url_for('projects.get_project', project_id=project.id))
    return render_template('add_user_to_project.html', user=current_user, form=form, legend='Add User To Project')

@projects.route('/remove-user-from-project/<string:project_id>/<string:user_id>', methods=['GET', 'POST'])
@login_required
def remove_user_from_project(project_id, user_id):
    project = Project.query.get_or_404(project_id)
    user = User.query.get_or_404(user_id)
    if project.manager().id != current_user.id:
        abort(403)
    if user.id == project.manager().id:
        flash('Cannot remove the project manager from the project!', category='danger')
        return redirect(url_for('projects.get_project', project_id=project.id))
    db.session.query(project_user).filter(
        project_user.c.project_id == project.id,
        project_user.c.user_id == user.id
    ).delete()
    db.session.commit()
    flash('User removed from project!', category='success')
    return redirect(url_for('projects.get_project', project_id=project.id))

@projects.route('/update-user-role/<string:project_id>/<string:user_id>', methods=['GET', 'POST'])
@login_required
def update_user_role(project_id, user_id):
    project = Project.query.get_or_404(project_id)
    user = User.query.get_or_404(user_id)
    if project.manager().id != current_user.id:
        abort(403)
    if user.id == project.manager().id:
        flash('Cannot update the project manager role!', category='danger')
        return redirect(url_for('projects.get_project', project_id=project.id))
    method = request.form.get('_method')
    form = ProjectUserForm(project_id, method)
    form.email.data = user.email
    if form.validate_on_submit():
        db.session.query(project_user).filter(
            project_user.c.project_id == project.id,
            project_user.c.user_id == user.id
        ).update({'user_role': form.role.data, 'updated_by': str(current_user.id)})
        db.session.commit()
        flash('User role updated!', category='success')
        return redirect(url_for('projects.get_project', project_id=project.id))
    elif request.method == 'GET':
        form.role.data = db.session.query(project_user).filter(
            project_user.c.project_id == project.id,
            project_user.c.user_id == user.id
        ).first().user_role
    return render_template('add_user_to_project.html', user=current_user, form=form, legend='Update User Role')

track_it_all/users/routes.py
import uuid
from flask import Blueprint, render_template, request, flash, redirect, url_for
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, logout_user, current_user, login_required

from track_it_all import db

from track_it_all.models import User
from track_it_all.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from track_it_all.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.email = form.email.data
        current_user.first_name = form.first_name.data
        current_user.last_name = form.last_name.data
        db.session.commit()
        flash('Account updated!', category='success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.email.data = current_user.email
        form.first_name.data = current_user.first_name
        form.last_name.data = current_user.last_name
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', user=current_user, image_file=image_file, form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=form.remember.data)
                next_page = request.args.get('next')
                return redirect(next_page) if next_page else redirect(url_for('main.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
    return render_template('login.html', user=current_user, form=form)

@users.route('/sign-up', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        email = form.email.data
        first_name = form.first_name.data
        last_name = form.last_name.data
        password = form.password1.data

        new_user = User(email=email, first_name=first_name, last_name=last_name, password=generate_password_hash(password))
        db.session.add(new_user)
        db.session.commit()
        login_user(new_user, remember=True)
        flash('Account created!', category='success')
        return redirect(url_for('main.home'))
    return render_template('sign_up.html', user=current_user, form=form)

@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/reset-password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            send_reset_email(user)
            flash('An email has been sent with instructions to reset your password.', category='info')
            return redirect(url_for('users.login'))
        else:
            flash('Email does not exist.', category='error')
    return render_template('reset_request.html', user=current_user, form=form)

@users.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', category='warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        user.password = generate_password_hash(form.password1.data)
        db.session.commit()
        flash('Your password has been updated!', category='success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', user=current_user, form=form)

track_it_all/templates/bug.html
{% extends "base.html" %} 

{% block title %}Bug Description{% endblock %} 

{% block content%}

<div class="container">
  <h1 class="mt-5 mb-4">This is the Bug Description page</h1>

  {% if user.is_authenticated %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata mb-3">
          <h5>{{ user_assigned.first_name }}</h5>
            <div>
              <a class="btn btn-secondary btn-sm me-1" href="{{ url_for('bugs.update_bug', bug_id=bug.id) }}">Update</a>
              <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
            </div>
        </div>
        <h2 class="article-title">{{ bug.title }}</h2>
        <p class="article-content">{{ bug.about }}</p>
        <h5>{{ bug.user_assigned.first_name }}</h5>
        <h4>{{ bug.priority }}</h4>
        <h4>{{ bug.bug_status }}</h4>
      </div>
    </article>

    <!-- Delete Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Bug?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <form action="{{ url_for('bugs.delete_bug', bug_id=bug.id) }}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>

  {% else %}
    <h1 class="mt-5 mb-4">Welcome, Guest</h1>
    <a class="btn btn-secondary btn-sm me-1" href="/login">Login</a>
    <a class="btn btn-secondary btn-sm" href="/sign-up">Sign Up</a>
  {% endif %}
</div>

{% endblock %}

track_it_all/templates/project.html
{% extends "base.html" %} 

{% block title %}Project Description{% endblock %} 

{% block content%}

<div class="container">
  <h1 class="mt-5 mb-4">This is the Project Description page</h1>

  {% if user.is_authenticated %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata mb-3">
          <small class="text-muted">{{ project.created_at.strftime('%Y-%m-%d') }}</small>
          {% if project.manager() == user %}
            <div>
              <a class="btn btn-secondary btn-sm me-1" href="{{ url_for('projects.update_project', project_id=project.id) }}">Update</a>
              <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
            </div>
          {% endif %}
        </div>
        <h2 class="article-title">{{ project.name }}</h2>
        <p class="article-content">{{ project.about }}</p>
        {% if project.group_project %}
          <p class="article-content">This is a group project</p>
          <h4>Manager</h4>
          <p class="article-content">{{ project.manager().first_name }}</p>
          <h4>Members</h4>
          <ul>
            {% for member in project.get_all_users() %}
            {% if member != project.manager() %}
              <li>{{ member.first_name }} - {{ member.get_role(project.id) }}</li>
              {% if project.manager() == user %}
              <div>
                <a class="btn btn-secondary btn-sm me-1" href="{{ url_for('projects.update_user_role', project_id=project.id, user_id=member.id) }}">Update Role </a>
                <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#confirmRemoveModal{{ member.id }}">
                  Remove {{ member.first_name }}
                </button>
              </div>
                
                <!-- Confirmation Modal for Removing Member -->
                <div class="modal fade" id="confirmRemoveModal{{ member.id }}" tabindex="-1" aria-labelledby="confirmRemoveModal{{ member.id }}Label" aria-hidden="true">
                  <div class="modal-dialog">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="confirmRemoveModal{{ member.id }}Label">Remove {{ member.first_name }} from project?</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                        <form action="{{ url_for('projects.remove_user_from_project', project_id=project.id, user_id=member.id) }}" method="POST">
                          <input class="btn btn-danger" type="submit" value="Remove">
                        </form>
                      </div>
                    </div>
                  </div>
                </div>
                
              {% endif %}
          {% endif %}
          </ul>
          {% endfor %}
        {% else %}
          <p class="article-content">This is an individual project</p>
        {% endif %}

        <h2>Bugs</h2>
        <ul>
          {% for bug in project.get_all_bugs() %}
          <li>
            <small><a href="{{ url_for('bugs.user_bugs', user_id=user.id) }}">{{ bug.assigned_user.first_name }}</a></small>
            <br>
            <a href="{{ url_for('bugs.get_bug', bug_id=bug.id) }}">{{ bug.title }}</a> - {{ bug.priority }}
            <div>
              <a class="btn btn-secondary btn-sm me-1" href="{{ url_for('bugs.update_bug', bug_id=bug.id) }}">Update Bug</a>
              <!-- Button trigger modal -->
              <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal{{ bug.id }}">
                Delete Bug
              </button>
            </div>
          </li>
          {% endfor %}
        </ul>

        <!-- Delete Modal -->
        {% for bug in project.get_all_bugs() %}
        <div class="modal fade" id="deleteModal{{ bug.id }}" tabindex="-1" aria-labelledby="deleteModalLabel{{ bug.id }}" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLabel{{ bug.id }}">Delete Bug?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form action="{{ url_for('bugs.delete_bug', bug_id=bug.id) }}" method="POST">
                  <input class="btn btn-danger" type="submit" value="Delete">
                </form>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}

        <br>
        <br>
        <br>
          <a class="btn btn-secondary btn-sm me-1" href="{{ url_for('bugs.add_bug', project_id=project.id) }}">Add Bug</a>
        {% if project.manager() == user %}
        <a class="btn btn-secondary btn-sm" href="{{ url_for('projects.add_user_to_project', project_id=project.id) }}">Add User</a>
        {% endif %}
      </div>
    </article>

    <!-- Delete Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Project?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <form action="{{ url_for('projects.delete_project', project_id=project.id) }}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>

  {% else %}
    <h1 class="mt-5 mb-4">Welcome, Guest</h1>
    <a class="btn btn-secondary btn-sm me-1" href="/login">Login</a>
    <a class="btn btn-secondary btn-sm" href="/sign-up">Sign Up</a>
  {% endif %}
</div>

{% endblock %}

track_it_all/templates/user_bugs.html
{% extends "base.html" %} 
{% block title %}Bugs{% endblock %} 
{% block content%}
  <h1 class="mb-3">Bugs by {{user.first_name}} ({{ bugs.total }})</h1>
  {% for bug in bugs.items %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
            <div>
              <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('bugs.update_bug', bug_id=bug.id) }}">Update</a>
              <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
            </div>
        </div>
        <h2><a class="article-title" href="{{ url_for('bugs.get_bug', bug_id=bug.id) }}">{{ bug.title }}</a></h2>
        <p class="article-content">{{ bug.about }}</p>
      </div>
    </article>

    <!-- Delete Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Bug?</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <form action="{{ url_for('bugs.delete_bug', bug_id=bug.id) }}" method="POST">
              <input class="btn btn-danger" type="submit" value="Delete">
            </form>
          </div>
        </div>
      </div>
    </div>
  {% endfor %}

  {% for page_num in bugs.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if bugs.page == page_num %}
        <a class="btn btn-primary mb-4 active" href="{{ url_for('bugs.user_bugs', user_id=user.id, page=page_num) }}"><b>{{ page_num }}</b></a>
      {% else %}
        <a class="btn btn-outline-primary mb-4" href="{{ url_for('bugs.user_bugs', user_id=user.id, page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}

  {% if bugs.has_next %}
    <a class="btn btn-primary mb-4" href="{{ url_for('bugs.user_bugs', user_id=user.id, page=bugs.next_num) }}">Next</a>
  {% endif %}
  {% if bugs.has_prev %}
    <a class="btn btn-outline-primary mb-4" href="{{ url_for('bugs.user_bugs', user_id=user.id, page=bugs.prev_num) }}">Prev</a>
  {% endif %}
{% endblock %}

track_it_all/templates/user_projects.html
{% extends "base.html" %} 
{% block title %}Projects{% endblock %} 
{% block content%}
  <h1 class="mb-3">Projects assigned to {{user.first_name}} ({{ projects.total }} no.s)</h1>
  {% for project in projects.items %}
    <article class="media content-section">
      <div class="media-body">
        <div class="article-metadata">
          <small class="text-muted">{{ project.created_at.strftime('%Y-%m-%d') }}</small>
          {% if project.manager() == user %}
            <div>
              <a class="btn btn-secondary btn-sm me-1" href="{{ url_for('projects.update_project', project_id=project.id) }}">Update</a>
              <button type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
            </div>
          {% endif %}
        </div>
        <h2 class="article-title">{{ project.name }}</h2>
        <p class="article-content">{{ project.about }}</p>
        {% if project.group_project %}
          <p class="article-content">This is a group project</p>
        {% else %}
            <p class="article-content">This is an individual project</p>
        {% endif %}
        {% if project.manager() == user %}
            <a class="btn btn-secondary btn-sm me-1" href="{{ url_for('bugs.add_bug', project_id=project.id) }}">Add Bug</a>
        {% endif %}
      </div>
    </article>
  {% endfor %}

  {% for page_num in projects.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
      {% if projects.page == page_num %}
        <a class="btn btn-primary mb-4 active" href="{{ url_for('projects.user_projects', user_id=user.id, page=page_num) }}"><b>{{ page_num }}</b></a>
      {% else %}
        <a class="btn btn-outline-primary mb-4" href="{{ url_for('projects.user_projects', user_id=user.id, page=page_num) }}">{{ page_num }}</a>
      {% endif %}
    {% else %}
      ...
    {% endif %}
  {% endfor %}

  {% if projects.has_next %}
    <a class="btn btn-primary mb-4" href="{{ url_for('projects.user_projects', user_id=user.id, page=projects.next_num) }}">Next</a>
  {% endif %}
  {% if projects.has_prev %}
    <a class="btn btn-outline-primary mb-4" href="{{ url_for('projects.user_projects', user_id=user.id, page=projects.prev_num) }}">Prev</a>
  {% endif %}
{% endblock %}